spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    # 参数配置，显示sql
    props:
      sql:
        show: true    # 配置数据源
    datasource:      # 给每个数据源取别名，下面的ds1,ds2,ds3任意取名字
      names: ds0,ds1,ds2      # 给master-ds1每个数据源配置数据库连接信息
      ds0:        # 配置druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://10.0.0.138:3306/master_slave_2021
        username: root
        password: 123456
        maxPoolSize: 100
        minPoolSize: 5
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://10.0.0.138:3307/master_slave_2022
        username: root
        password: 123456
        maxPoolSize: 100
        minPoolSize: 5
      ds2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://10.0.0.138:3308/master_slave_2023
        username: root
        password: 123456
        maxPoolSize: 100
        minPoolSize: 5
    sharding:
      default-data-source-name: ds0
      tables:
        user:
          actual-data-nodes: ds$->{0..2}.user$->{0..2}
          database-strategy:
            standard:
              sharding-column: birthday
              precise-algorithm-class-name: com.crow.config.BirthdayAlgorithm
          table-strategy:
            inline:
              sharding-column: age
              algorithm-expression: user$->{age % 3}



